version: '3'
services:
  fluentd:
    image: fluent/fluentd:edge
    container_name: docker-fluentd
    user: root
    volumes:
      - ./logs:/fluentd/log
    ports:
      - 24224:24224

  tester:
    image: busybox
    container_name: docker-tester
    command: "echo 'Hello from tester'"
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.{.ID}}"
        fluentd-address: "localhost:24224"

